[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_RECOVER_KOVAN_ADDRESS='0x1048b5f9c7c7d52dcd5c445709686accd4fd2a82'
  REACT_APP_ARBITRATOR_KOVAN_ADDRESS='0x91be318eca5df3713551e8ae66735f1f1cea8cec'
  REACT_APP_WEB3_KOVAN_FALLBACK_URL='wss://kovan.infura.io/ws/v3/846256afe0ee40f0971d902ea8d36266'
  REACT_APP_DRAW_EVENT_LISTENER_BLOCK_NUMBER='7303699'

[context.production.environment]
  REACT_APP_RECOVER_MAINNET_ADDRESS='0x38E7bdC018396c3cb94ac50fD9c642021B8A5aCC'
  REACT_APP_ARBITRATOR_MAINNET_ADDRESS='0xd1b286456978dfcd8eac84dc801d98a48634ee32'
  REACT_APP_WEB3_MAINNET_FALLBACK_URL='wss://mainnet.infura.io/ws/v3/846256afe0ee40f0971d902ea8d36266'
  REACT_APP_DRAW_EVENT_LISTENER_BLOCK_NUMBER='7303699'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build"
  functions = "lambda"