[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_RECOVER_KOVAN_ADDRESS='0xa0ca0d19cab7d2064b620f80a692b275d94f0ed4'
  REACT_APP_ARBITRATOR_KOVAN_ADDRESS='0x1ee318dbc19267dbce08f54a66ab198f73ede356'
  REACT_APP_WEB3_FALLBACK_URL='wss://mainnet.infura.io/ws'
  REACT_APP_PATCH_USER_SETTINGS_URL=''

[context.production.environment]
  REACT_APP_PATCH_USER_SETTINGS_URL=''

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
