[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_URL_APP='https://app.recover.ws'
  REACT_APP_RECOVER_KOVAN_ADDRESS='0x8B47e24Cad8b658a3639B0342A21632d3C494C29'
  REACT_APP_ARBITRATOR_KOVAN_ADDRESS='0x91be318eca5df3713551e8ae66735f1f1cea8cec'
  REACT_APP_WEB3_KOVAN_FALLBACK_URL='wss://kovan.infura.io/ws/v3/846256afe0ee40f0971d902ea8d36266'
  REACT_APP_DRAW_EVENT_LISTENER_BLOCK_NUMBER='7303699'

[context.production.environment]
  REACT_APP_URL_APP='https://app.recover.ws'
  REACT_APP_RECOVER_MAINNET_ADDRESS='0x02C86846887faa1d964a838Dc50739B49c8329bc'
  REACT_APP_ARBITRATOR_MAINNET_ADDRESS='0xd1b286456978dfcd8eac84dc801d98a48634ee32'
  REACT_APP_WEB3_MAINNET_FALLBACK_URL='wss://mainnet.infura.io/ws/v3/846256afe0ee40f0971d902ea8d36266'
  REACT_APP_DRAW_EVENT_LISTENER_BLOCK_NUMBER='7303699'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build"
  functions = "lambda"