[build.environment]
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_RECOVER_KOVAN_ADDRESS='0xe108942a97f02c21BAe85c3e16a3e58E8be2caB9'
  REACT_APP_ARBITRATOR_KOVAN_ADDRESS='0xd1b286456978dfcd8eac84dc801d98a48634ee32'
  REACT_APP_WEB3_FALLBACK_URL='wss://kovan.infura.io/ws/v3/8886cb30669f45a19e3c42a0d81d7ebd'

[context.production.environment]
  REACT_APP_RECOVER_KOVAN_ADDRESS='0xe108942a97f02c21BAe85c3e16a3e58E8be2caB9'
  REACT_APP_ARBITRATOR_KOVAN_ADDRESS='0xd1b286456978dfcd8eac84dc801d98a48634ee32'
  REACT_APP_WEB3_FALLBACK_URL='wss://kovan.infura.io/ws/v3/8886cb30669f45a19e3c42a0d81d7ebd'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build"
  functions = "lambda"